[[redirects]]
from = "/fourier/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/fourier"
to = "/fourier/"
status = 301

[[redirects]]
from = "/fourier/"
to = "/index.html"
status = 200